[package]
name = "tptp2json"
version = "0.2.0"
authors = ["Michael Rawson <michael@rawsons.uk>"]
edition = "2018"

[dependencies]
serde_json = "1.0"

[dependencies.tptp]
path = "../"
features = ["serde"]
